services:

  db:
    image: mysql:8.0

    restart: always

    environment:
      MYSQL_DATABASE: fastapi_banking
      MYSQL_ROOT_PASSWORD: bankingsys123

    ports:
      - "3308:3306"

    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .

    env_file:
      - .env.docker

    ports:
      - "8001:8000"

    depends_on:
      - db

    command: >
      sh -c "
      sleep 20 &&
      uvicorn bankingsys:app
      --host 0.0.0.0
      --port 8000
      "

volumes:
  mysql_data: